name:                valid-bst
version:             0.1.0.0
github:              "maruks/valid-bst"
license:             BSD3
author:              "Maris Orbidans"
maintainer:          "maris.orbidans@gmail.com"
copyright:           "2018 Maris Orbidans"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maruks/valid-bst#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  valid-bst-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - valid-bst

tests:
  valid-bst-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - valid-bst
